import { type Metadata } from 'next'
import { Container } from '@/components/Container'
import { AppScreenshot } from '@/components/AppScreenshot'
import { Button } from '@/components/Button'
import { CallToAction } from '@/components/CallToAction'

export const metadata: Metadata = { title: 'Features', description: 'Explore Rallymetrica’s tennis tracking, live coach–player updates, assigned patterns of play and execution results, reports, replay, and player statistics.' }

const features = [
  { label: '01 / On court', title: 'Track the match your way.', description: 'A busy match deserves a practical tracker. Start with point winners, add rally counts and endings, or record every landing. You choose how much detail to capture.', screen: 'live', alt: 'Detailed live match tracking court', href: 'tracking-modes', bullets: ['Score only: point winners and scoring', 'Counter: shot counts and point endings', 'Detailed: court placements and pattern matching', 'Undo mistakes and resume a live match'] },
  { label: '02 / After the point', title: 'See how the result happened.', description: 'Momentum, aggression, serve, return, pressure, landings. Explore the report page by page and use situation and score filters to ask a more specific question.', screen: 'momentum', alt: 'Match momentum and its biggest swings', href: 'reports-and-replay', bullets: ['Momentum: who was ahead, and the swings that decided it', 'Aggression: points built against points given away, game by game', 'Situation, score, and set filters on every page', 'Placement and landing views with Detailed tracking'] },
  { label: '03 / A closer look', title: 'Revisit the rally.', description: 'Follow recorded point data back onto the court. Move by shot, point, game, or set, and return to a moment from the timeline or momentum strip.', screen: 'replay', alt: 'Recorded rally replay court', href: 'reports-and-replay', bullets: ['Animated replay from recorded placements', 'Play, pause, and move through available units', 'Review a finished match or replay so far', 'Full rally paths require Detailed tracking; replay is not video'] },
  { label: '04 / Over time', title: 'Give every match some context.', description: 'A result is easier to understand when you can see what came before it. Follow every metric — aggression included — over your last 3, 7, 10 or all matches, head to head against an opponent, with a moving average and a trend line.', screen: 'stats', alt: 'Player trend chart across recorded matches', href: 'stats-and-trends', bullets: ['Player profiles and match history', 'Every metric over a match window', 'Head-to-head against any opponent you have faced', 'Moving average and trend, coloured above and below'] },
  { label: '05 / Stay connected', title: 'Follow your player.', emphasis: 'From your phone.', description: 'Link a coach and player once, then follow the match as the points land — in the background, with a notification every set, game or point. The coach sees the score, opens the report, and revisits recorded rallies on their own phone.', screen: 'home', alt: 'A student’s live match on the coach’s Home screen', href: 'coach-player-link', bullets: ['Linking by code, with the player’s approval', 'Every saved point arrives live, end-to-end encrypted', 'Notifications per student: live scores by set, game or point', 'Offline updates sync when connectivity returns'] },
  { label: '06 / Patterns of play', title: 'Create the plan.', emphasis: 'Measure the execution.', description: 'Draw a pattern of play and assign it to your players. Include it in Detailed tracking to see how often the full sequence was executed and how many of those points were won.', screen: 'patterns', alt: 'Coach pattern creation and player assignments', href: 'coaching-patterns', bullets: ['Create from a blank court or a template', 'Assigned patterns sync to linked players', 'Up to three selected patterns per player', 'Completed sequences out of attempts, plus point win rate after completion'] },
]

export default function Features() {
  return <><Container className="py-16 sm:py-24"><p className="eyebrow text-accent">Meet Rallymetrica</p><h1 className="mt-5 max-w-3xl text-5xl leading-[1.08] font-semibold tracking-[-.055em] sm:text-6xl">Your tennis.<br /><span className="text-accent">With more perspective.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted">From the score in front of you to the pattern behind it. Explore the tools that connect tracking, understanding, and progress.</p></Container>{features.map((feature,index) => <section key={feature.title} className={`border-t border-white/10 py-16 sm:py-24 ${index % 2 === 0 ? 'bg-surface/40' : ''}`}><Container className="grid items-center gap-12 lg:grid-cols-2 lg:gap-24"><div className={index % 2 ? 'lg:order-2' : ''}><p className="eyebrow text-accent">{feature.label}</p><h2 className="section-heading mt-5 max-w-lg">{feature.title}{feature.emphasis && <> <span className="text-accent">{feature.emphasis}</span></>}</h2><p className="mt-6 max-w-lg leading-7 text-muted">{feature.description}</p><ul className="mt-7 space-y-3">{feature.bullets.map(bullet => <li key={bullet} className="flex gap-3 text-sm leading-6"><span className="text-accent" aria-hidden="true">✓</span>{bullet}</li>)}</ul><Button href={`/learn/${feature.href}`} variant="outline" className="mt-8">Read the guide ↗</Button></div><AppScreenshot name={feature.screen} alt={feature.alt} className="mx-auto w-[250px] sm:w-[280px]" /></Container></section>)}<CallToAction /></>
}
