import { Container } from '@/components/Container'
import { appStoreUrl } from '@/lib/site'

const faqs = [
  { question: 'Where can I get Rallymetrica?', answer: appStoreUrl ? 'Use the App Store link on this website to open Rallymetrica’s Apple listing. Start with the Learn section for a walkthrough of your first match.' : 'Rallymetrica is not live yet. When it launches, this website will link directly to its Apple App Store listing. You can explore the features and guides here in the meantime.' },
  { question: 'Do I have to track every shot?', answer: 'No. Choose Score to record point winners, Counter to add shot counts and point endings, or Detailed to tap every landing. The insight available afterward depends on the detail you record.' },
  { question: 'Does rally replay show video?', answer: 'Replay animates the point data recorded in the app. It is not a video recording. Detailed tracking captures the court placements needed to show full rally paths.' },
  { question: 'Can I correct a point or leave a match unfinished?', answer: 'Yes. Undo reverses recorded actions, and a live match remains available to Resume when you return to the app.' },
  { question: 'Can my coach follow my match from their phone?', answer: 'Yes. A player displays their QR code in Settings → Coach; the coach scans it in Settings → Students → Add student, and the player approves the link. The coach receives updates after each saved point and can open the report or Replay so far. Offline updates are queued until connectivity returns.' },
  { question: 'Where is my data stored, and is sharing encrypted?', answer: 'Your recorded match history is stored locally on your phone; your linked coach receives read-only copies on theirs. Shared match content is end-to-end encrypted. The delivery relay queues encrypted messages until retrieval and keeps device and connection details, so some encrypted data and routing information do pass through a server.' },
  { question: 'What happens when I unlink my coach?', answer: 'New sharing stops on your phone. Once the coach’s app is online and receives the unlink, it removes match copies received through that link. Your original recordings remain. Matches the coach recorded independently and copies already exported or shared outside the link remain too. Pausing a link stops updates and keeps received copies.' },
  { question: 'Can a coach assign patterns and track their success?', answer: 'Yes. On Coach, create patterns of play and assign them to linked players. Include up to three patterns per player in Detailed match setup. The Patterns report shows completed sequences out of attempts and the percentage of points won when the pattern was completed. Results come from the recorded court landings.' },
  { question: 'Where should I start learning?', answer: 'Start with Your first match in the Learn section. Next, compare the tracking modes, then follow the live tracking and match report guides.' },
]

export function Faqs() {
  return <section id="faqs" className="border-t border-white/10 py-20 sm:py-24"><Container><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><p className="eyebrow text-accent">A few things to know</p><h2 className="section-heading mt-5">Good questions.<br /><span className="text-accent">Clear answers.</span></h2></div><div>{faqs.map(faq => <details key={faq.question} className="group border-b border-white/10 py-6 first:border-t"><summary className="flex list-none items-center justify-between gap-6 text-base font-medium [&::-webkit-details-marker]:hidden">{faq.question}<span className="text-xl text-accent transition-transform group-open:rotate-45" aria-hidden="true">+</span></summary><p className="mt-4 pr-7 text-sm leading-7 text-muted">{faq.answer}</p></details>)}</div></div></Container></section>
}
