import Link from 'next/link'
import { Container } from '@/components/Container'
import { appStoreUrl } from '@/lib/site'

const faqs: { question: string; answer: string; href?: string; linkText?: string }[] = [
  { question: 'Where can I get Rallymetrica?', answer: appStoreUrl ? 'Use the App Store link on this website to open Rallymetrica’s Apple listing. Start with the Learn section for a walkthrough of your first match.' : 'Rallymetrica is in beta on TestFlight ahead of its App Store release. When it launches, this website will link directly to its Apple listing. You can explore the features and guides here in the meantime.' },
  { question: 'What does it cost?', answer: 'Rallymetrica is free to download. The Free plan scores every match and includes two detailed matches to try. Player ($6.99 a month or $69.99 a year) adds detailed tracking on every match, the full stats engine and the coach link; Coach ($99.99 a year, as Coach for up to 5 students or Academy for up to 25) adds the roster, play patterns and notifications. Every subscription starts with a 7-day free trial through the App Store.' },
  { question: 'Do I have to track every shot?', answer: 'No. Choose Score to record point winners, Counter to add point endings, or Detailed to tap every landing. The insight available afterward depends on the detail you record.' },
  { question: 'What are momentum and aggression?', answer: 'Momentum shows who was ahead as the match went on and where it swung. Aggression shows how: points built — aces, winners and errors forced from the opponent — against points given away — unforced errors, double faults and errors off a sitter. The report shows the margin and the efficiency game by game, and Stats tracks both across a season.' },
  { question: 'How are the numbers calculated?', answer: 'Every statistic comes from the points you tapped, under the rules of the match — nothing is estimated from video or sensors. The stats engine reference lists each metric, the tracking level it needs and exactly how it is counted, from break points saved to the aggressive margin.', href: '/learn/stats-engine', linkText: 'Read the stats engine reference' },
  { question: 'Does rally replay show video?', answer: 'Replay animates the point data recorded in the app. It is not a video recording. Detailed tracking captures the court placements needed to show full rally paths.' },
  { question: 'Can I correct a point or leave a match unfinished?', answer: 'Yes. Undo reverses recorded actions, and a live match remains available to Resume when you return to the app.' },
  { question: 'Can my coach follow my match from their phone?', answer: 'Yes. A player shows their code in Settings → Coach link; the coach scans it in Settings → Students → Add student, and the player taps Link. From then on every saved point reaches the coach’s phone as it lands, with a notification every set, game or point — the coach chooses. Points sent while a phone is offline queue up and arrive when it reconnects.' },
  { question: 'Where is my data stored, and is sharing encrypted?', answer: 'Your matches are stored on your phone, never in a cloud; a linked coach receives read-only copies on theirs. Everything sent between the two phones is end-to-end encrypted — the relay only passes sealed envelopes along and keeps the device and connection details needed to deliver them. A backup you save under Settings → Data is a file you keep.', href: '/privacy', linkText: 'Read the privacy policy' },
  { question: 'What happens when I unlink my coach?', answer: 'New sharing stops on your phone. Once the coach’s app is online and receives the unlink, it removes match copies received through that link. Your original recordings remain. Matches the coach recorded independently and copies already exported or shared outside the link remain too. Pausing a link stops updates and keeps received copies.' },
  { question: 'Can a coach assign patterns and track their success?', answer: 'Yes. On Coach, draw patterns of play and assign them to linked players. Include up to three patterns per player in Detailed match setup. The Patterns report shows how often each pattern was played and how often those points were won. Results come from the recorded court landings.' },
  { question: 'Where should I start learning?', answer: 'Start with Your first match in the Learn section. Next, compare the tracking modes, then follow the live tracking and match report guides.' },
]

export function Faqs() {
  return <section id="faqs" className="border-t border-white/10 py-20 sm:py-24"><Container><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><p className="eyebrow text-accent">A few things to know</p><h2 className="section-heading mt-5">Good questions.<br /><span className="text-accent">Clear answers.</span></h2></div><div>{faqs.map(faq => <details key={faq.question} className="group border-b border-white/10 py-6 first:border-t"><summary className="flex list-none items-center justify-between gap-6 text-base font-medium [&::-webkit-details-marker]:hidden">{faq.question}<span className="text-xl text-accent transition-transform group-open:rotate-45" aria-hidden="true">+</span></summary><p className="mt-4 pr-7 text-sm leading-7 text-muted">{faq.answer}</p>{faq.href && <Link href={faq.href} className="mt-3 inline-block text-sm font-semibold text-accent">{faq.linkText} <span aria-hidden="true">↗</span></Link>}</details>)}</div></div></Container></section>
}
